project 'SwpBluetoothDemo.xcodeproj'
# Uncomment the next line to define a global platform for your project
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'

target 'SwpBluetoothDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpBluetoothDemo
  pod 'SwpBluetooth', :path => '../'
  
  
  pod 'Masonry'
  pod 'SwpCateGory/SwpColor'
  pod 'SwpCateGory/SwpSetButton'
  pod 'SwpCateGory/SwpNavigationBar'
  pod 'SwpCateGory/SwpSetNavigationBarItem'
  

end
